### ISSUE TITLE
unexpected behavior when reciprocal_weights contains Inf

### ISSUE THREAD

**Issue by gaelforget** [LevineLab/EpiGen#1]
Thank you @LevineLab  for providing the EpiGen code as open source.

I am opening this issue to report an apparent problem with `reciprocal_weights` having `Inf` values. This happens for all individuals that have not had any genetic mutation (`population.co(:,5)=0`). The resulting `sampled_index` computed by `randsample` just after is all `1`, which I don't think is the intention.  

It seems that this can be solved by replacing `0` with a small constant as done in <https://github.com/LevineLab/EpiGen/compare/master...gaelforget:gf1>

Hopefully I did not miss something obvious, but I thought it might be useful to report this to you here.

**Comment by nmlevine** [comment]
THANK YOU Gael! This has been fixed.
